import type {
    IPropertyCodeAndIds,
    IAddonAnalytics,
    IAnalyticsData,
    IBookingSourceAnalytics,
    IGuestAnalytics,
    IGuestTypeBreakdown,
    // IHousekeepingAnalytics,
    IPaymentMethodAnalytics,
    IPaymentMethodBreakdown,
    IPaymentStatusBreakdown,
    IPopularAddon,
    // IPriorityBreakdown,
    IReservationAnalytics,
    IReservationStatusBreakdown,
    IRevenueAnalytics,
    IRoomAnalytics,
    IRoomStatusBreakdown,
    IRoomTypeStats,
    ISourceBreakdown,
    // ITaskStatusBreakdown,
    ITopPerformingProperties,
    ITopPropertyByBookings,
    ITopPropertyByOccupancy,
    ITopPropertyByRevenue,
    ICountryBreakdown,
    IRoomTypeOccupancy,
    ILoader,
    IComparisonPeriod,
    IStatisticMetric,
    IStatisticsComparison
} from "./dash.type";


export type {
    IPropertyCodeAndIds,
    IAddonAnalytics,
    IAnalyticsData,
    IBookingSourceAnalytics,
    IGuestAnalytics,
    IGuestTypeBreakdown,
    // IHousekeepingAnalytics,
    IPaymentMethodAnalytics,
    IPaymentMethodBreakdown,
    IPaymentStatusBreakdown,
    IPopularAddon,
    // IPriorityBreakdown,
    IReservationAnalytics,
    IReservationStatusBreakdown,
    IRevenueAnalytics,
    IRoomAnalytics,
    IRoomStatusBreakdown,
    IRoomTypeStats,
    ISourceBreakdown,
    // ITaskStatusBreakdown,
    ITopPerformingProperties,
    ITopPropertyByBookings,
    ITopPropertyByOccupancy,
    ITopPropertyByRevenue,
    ICountryBreakdown,
    IRoomTypeOccupancy,
    ILoader,
     IComparisonPeriod,
    IStatisticMetric,
    IStatisticsComparison
}